version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: devsu_test
      POSTGRES_PASSWORD: devsu_test
      POSTGRES_DB: devsu_test
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  microservicio-cliente:
    build: ./Cliente
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/devsu_test
      SPRING_DATASOURCE_USERNAME: devsu_test
      SPRING_DATASOURCE_PASSWORD: devsu_test
    depends_on:
      - postgres

  microservicio-cuenta:
    build: ./Cuenta
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/devsu_test
      SPRING_DATASOURCE_USERNAME: devsu_test
      SPRING_DATASOURCE_PASSWORD: devsu_test
      MICROSERVICIO_CLIENTE_URL: http://microservicio-cliente:8080
    depends_on:
      - postgres

volumes:
  postgres-data: